# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa')),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(verbose_name='Ilość')),
                ('expiration_date', models.DateField(verbose_name='Data ważności')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refrigerator.Category', verbose_name='Kategoria:')),
            ],
        ),
    ]
