# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import refrigerator.validators


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(validators=[refrigerator.validators.valid_range], verbose_name='Ilość'),
        ),
    ]
